from random import choice
from character import mean_soul_cost


treasures = {
    "Adventurer's Armour": {"set": "Characters Expansion", "strength": 14, "dexterity": 22, "intelligence": 14, "faith": 0},
    "Alonne Captain Armour": {"set": "Iron Keep", "strength": 25, "dexterity": 0, "intelligence": 25, "faith": 0},
    "Alonne Greatbow": {"set": "Iron Keep", "strength": 20, "dexterity": 20, "intelligence": 0, "faith": 0},
    "Alonne Knight Armour": {"set": "Iron Keep", "strength": 20, "dexterity": 0, "intelligence": 20, "faith": 0},
    "Antiquated Robes": {"set": "Darkroot", "strength": 0, "dexterity": 0, "intelligence": 15, "faith": 20},
    "Black Armour": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 20, "intelligence": 20, "faith": 0},
    "Black Bow of Pharis": {"set": "Iron Keep", "strength": 0, "dexterity": 33, "intelligence": 0, "faith": 0},
    "Black Firebombs": {"set": "Explorers", "strength": 0, "dexterity": 0, "intelligence": 20, "faith": 20},
    "Black Hand Armour": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 20, "intelligence": 20, "faith": 0},
    "Black Iron Armour": {"set": "Characters Expansion", "strength": 18, "dexterity": 0, "intelligence": 0, "faith": 12},
    "Black Knight Armour": {"set": "Characters Expansion", "strength": 26, "dexterity": 16, "intelligence": 0, "faith": 16},
    "Black Knight Greataxe": {"set": "Tomb of Giants", "strength": 20, "dexterity": 0, "intelligence": 20, "faith": 20},
    "Black Knight Sword": {"set": "Tomb of Giants", "strength": 20, "dexterity": 23, "intelligence": 0, "faith": 0},
    "Blacksteel Katana": {"set": "Iron Keep", "strength": 0, "dexterity": 23, "intelligence": 0, "faith": 0},
    "Blessed Gem": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 25},
    "Blessed Gem": {"set": "Tomb of Giants", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 25},
    "Blood Gem": {"set": "Dark Souls The Board Game", "strength": 15, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Blood Gem": {"set": "Painted World of Ariamis", "strength": 15, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Bloodshield": {"set": "Painted World of Ariamis", "strength": 33, "dexterity": 0, "intelligence": 0, "faith": 16},
    "Bonewheel Shield": {"set": "Tomb of Giants", "strength": 25, "dexterity": 15, "intelligence": 0, "faith": 0},
    "Brigand Axe": {"set": "Dark Souls The Board Game", "strength": 19, "dexterity": 0, "intelligence": 16, "faith": 0},
    "Brigand Axe": {"set": "Painted World of Ariamis", "strength": 19, "dexterity": 0, "intelligence": 16, "faith": 0},
    "Carthus Curved Greatsword": {"set": "Tomb of Giants", "strength": 0, "dexterity": 30, "intelligence": 19, "faith": 0},
    "Catarina Armour": {"set": "Characters Expansion", "strength": 22, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Chloranthy Ring": {"set": "Dark Souls The Board Game", "strength": 18, "dexterity": 18, "intelligence": 18, "faith": 18},
    "Chloranthy Ring": {"set": "Tomb of Giants", "strength": 18, "dexterity": 18, "intelligence": 18, "faith": 18},
    "Claws": {"set": "Explorers", "strength": 0, "dexterity": 20, "intelligence": 20, "faith": 0},
    "Claymore": {"set": "Dark Souls The Board Game", "strength": 30, "dexterity": 26, "intelligence": 0, "faith": 0},
    "Claymore": {"set": "Painted World of Ariamis", "strength": 30, "dexterity": 26, "intelligence": 0, "faith": 0},
    "Cleric Armour": {"set": "Tomb of Giants", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 24},
    "Court Sorcerer Robes": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 17, "intelligence": 22, "faith": 0},
    "Court Sorcerer Robes": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 17, "intelligence": 22, "faith": 0},
    "Crescent Moon Sword": {"set": "Iron Keep", "strength": 0, "dexterity": 17, "intelligence": 0, "faith": 17},
    "Cresent Axe": {"set": "Tomb of Giants", "strength": 22, "dexterity": 17, "intelligence": 0, "faith": 15},
    "Crimson Robes": {"set": "Characters Expansion", "strength": 0, "dexterity": 12, "intelligence": 22, "faith": 12},
    "Crystal Gem": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 25, "faith": 0},
    "Crystal Gem": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 25, "faith": 0},
    "Crystal Shield": {"set": "Darkroot", "strength": 18, "dexterity": 0, "intelligence": 0, "faith": 28},
    "Dark Armour": {"set": "Characters Expansion", "strength": 0, "dexterity": 20, "intelligence": 20, "faith": 0},
    "Dark Wood Giant Ring": {"set": "Explorers", "strength": 0, "dexterity": 26, "intelligence": 0, "faith": 0},
    "Deacon Robes": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 24},
    "Deacon Robes": {"set": "Tomb of Giants", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 24},
    "Demon Titanite": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 10, "faith": 10},
    "Divine Blessing": {"set": "Tomb of Giants", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 22},
    "Dragon Crest Shield": {"set": "Dark Souls The Board Game", "strength": 21, "dexterity": 0, "intelligence": 0, "faith": 21},
    "Dragon Crest Shield": {"set": "Tomb of Giants", "strength": 21, "dexterity": 0, "intelligence": 0, "faith": 21},
    "Dragon Scale": {"set": "Tomb of Giants", "strength": 10, "dexterity": 0, "intelligence": 0, "faith": 10},
    "Dragonslayer Greatbow": {"set": "Explorers", "strength": 23, "dexterity": 23, "intelligence": 0, "faith": 0},
    "Drang Armour": {"set": "Dark Souls The Board Game", "strength": 18, "dexterity": 14, "intelligence": 0, "faith": 0},
    "Drang Armour": {"set": "Painted World of Ariamis", "strength": 18, "dexterity": 14, "intelligence": 0, "faith": 0},
    "Dusk Crown Ring": {"set": "Darkroot", "strength": 0, "dexterity": 0, "intelligence": 30, "faith": 0},
    "East-West Shield": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 28, "faith": 0},
    "East-West Shield": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 28, "faith": 0},
    "Eastern Iron Shield": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 28, "intelligence": 0, "faith": 0},
    "Eastern Iron Shield": {"set": "Tomb of Giants", "strength": 0, "dexterity": 28, "intelligence": 0, "faith": 0},
    "Effigy Shield": {"set": "Dark Souls The Board Game", "strength": 10, "dexterity": 0, "intelligence": 0, "faith": 10},
    "Effigy Shield": {"set": "Painted World of Ariamis", "strength": 10, "dexterity": 0, "intelligence": 0, "faith": 10},
    "Embraced Armour of Favour": {"set": "Characters Expansion", "strength": 13, "dexterity": 0, "intelligence": 0, "faith": 23},
    "Exile Armour": {"set": "Dark Souls The Board Game", "strength": 26, "dexterity": 0, "intelligence": 0, "faith": 16},
    "Exile Armour": {"set": "Painted World of Ariamis", "strength": 26, "dexterity": 0, "intelligence": 0, "faith": 16},
    "Exile Greatsword": {"set": "Painted World of Ariamis", "strength": 30, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Fireball": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 23, "faith": 0},
    "Fireball": {"set": "Tomb of Giants", "strength": 0, "dexterity": 0, "intelligence": 23, "faith": 0},
    "Firebombs": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 15, "faith": 15},
    "Firebombs": {"set": "Tomb of Giants", "strength": 0, "dexterity": 0, "intelligence": 15, "faith": 15},
    "Firelink Armour": {"set": "Dark Souls The Board Game", "strength": 20, "dexterity": 0, "intelligence": 15, "faith": 0},
    "Firelink Armour": {"set": "Tomb of Giants", "strength": 20, "dexterity": 0, "intelligence": 15, "faith": 0},
    "Flameberge": {"set": "Iron Keep", "strength": 0, "dexterity": 35, "intelligence": 0, "faith": 0},
    "Force": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 12, "faith": 0},
    "Force": {"set": "Tomb of Giants", "strength": 0, "dexterity": 0, "intelligence": 12, "faith": 0},
    "Four-Pronged Plow": {"set": "Darkroot", "strength": 23, "dexterity": 0, "intelligence": 0, "faith": 23},
    "Giant's Halberd": {"set": "Explorers", "strength": 27, "dexterity": 0, "intelligence": 0, "faith": 23},
    "Gold-Hemmed Black Robes": {"set": "Characters Expansion", "strength": 0, "dexterity": 14, "intelligence": 14, "faith": 14},
    "Golden Ritual Spear": {"set": "Iron Keep", "strength": 0, "dexterity": 0, "intelligence": 24, "faith": 21},
    "Great Mace": {"set": "Dark Souls The Board Game", "strength": 21, "dexterity": 0, "intelligence": 0, "faith": 28},
    "Great Mace": {"set": "Tomb of Giants", "strength": 21, "dexterity": 0, "intelligence": 0, "faith": 28},
    "Great Magic Weapon": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 12, "faith": 12},
    "Great Magic Weapon": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 12, "faith": 12},
    "Great Scythe": {"set": "Explorers", "strength": 32, "dexterity": 21, "intelligence": 0, "faith": 0},
    "Greataxe": {"set": "Dark Souls The Board Game", "strength": 32, "dexterity": 22, "intelligence": 0, "faith": 0},
    "Greataxe": {"set": "Painted World of Ariamis", "strength": 32, "dexterity": 22, "intelligence": 0, "faith": 0},
    "Guardian Armour": {"set": "Characters Expansion", "strength": 0, "dexterity": 22, "intelligence": 22, "faith": 0},
    "Halberd": {"set": "Dark Souls The Board Game", "strength": 18, "dexterity": 0, "intelligence": 0, "faith": 31},
    "Halberd": {"set": "Tomb of Giants", "strength": 18, "dexterity": 0, "intelligence": 0, "faith": 31},
    "Hard Leather Armour": {"set": "Dark Souls The Board Game", "strength": 26, "dexterity": 26, "intelligence": 26, "faith": 0},
    "Hard Leather Armour": {"set": "Tomb of Giants", "strength": 26, "dexterity": 26, "intelligence": 26, "faith": 0},
    "Havel's Armour": {"set": "Characters Expansion", "strength": 23, "dexterity": 0, "intelligence": 23, "faith": 0},
    "Havel's Greatshield": {"set": "Explorers", "strength": 35, "dexterity": 0, "intelligence": 13, "faith": 13},
    "Heal": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 23},
    "Heal": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 23},
    "Heal Aid": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 13},
    "Heal Aid": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 13},
    "Heavy Gem": {"set": "Dark Souls The Board Game", "strength": 25, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Heavy Gem": {"set": "Painted World of Ariamis", "strength": 25, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Hollow Gem": {"set": "Darkroot", "strength": 0, "dexterity": 0, "intelligence": 15, "faith": 15},
    "Hollow Soldier Shield": {"set": "Tomb of Giants", "strength": 16, "dexterity": 0, "intelligence": 0, "faith": 19},
    "Hunter Armour": {"set": "Darkroot", "strength": 0, "dexterity": 34, "intelligence": 17, "faith": 0},
    "Kukris": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 15, "intelligence": 0, "faith": 0},
    "Kukris": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 15, "intelligence": 0, "faith": 0},
    "Life Ring": {"set": "Iron Keep", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 30},
    "Lightning Gem": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 15, "faith": 0},
    "Lightning Gem": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 15, "faith": 0},
    "Longbow": {"set": "Darkroot", "strength": 0, "dexterity": 18, "intelligence": 0, "faith": 0},
    "Lothric Knight Greatsword": {"set": "Painted World of Ariamis", "strength": 20, "dexterity": 20, "intelligence": 13, "faith": 13},
    "Mannikin Claws": {"set": "Darkroot", "strength": 0, "dexterity": 24, "intelligence": 24, "faith": 0},
    "Mask of the Child": {"set": "Tomb of Giants", "strength": 0, "dexterity": 0, "intelligence": 19, "faith": 13},
    "Master's Attire": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 30, "intelligence": 18, "faith": 0},
    "Master's Attire": {"set": "Tomb of Giants", "strength": 0, "dexterity": 30, "intelligence": 18, "faith": 0},
    "Morion Blade": {"set": "Iron Keep", "strength": 24, "dexterity": 24, "intelligence": 0, "faith": 0},
    "Morning Star": {"set": "Dark Souls The Board Game", "strength": 16, "dexterity": 0, "intelligence": 0, "faith": 19},
    "Morning Star": {"set": "Tomb of Giants", "strength": 16, "dexterity": 0, "intelligence": 0, "faith": 19},
    "Murakumo": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 27, "intelligence": 17, "faith": 0},
    "Murakumo": {"set": "Tomb of Giants", "strength": 0, "dexterity": 27, "intelligence": 17, "faith": 0},
    "Old Ironclad Armour": {"set": "Iron Keep", "strength": 34, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Painting Guardian Armour": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 32, "intelligence": 14, "faith": 0},
    "Paladin Armour": {"set": "Painted World of Ariamis", "strength": 24, "dexterity": 24, "intelligence": 0, "faith": 24},
    "Parrying Dagger": {"set": "Explorers", "strength": 0, "dexterity": 21, "intelligence": 21, "faith": 21},
    "Phoenix Parma Shield": {"set": "Iron Keep", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 20},
    "Pierce Shield": {"set": "Dark Souls The Board Game", "strength": 16, "dexterity": 10, "intelligence": 0, "faith": 0},
    "Pierce Shield": {"set": "Tomb of Giants", "strength": 16, "dexterity": 10, "intelligence": 0, "faith": 0},
    "Pike": {"set": "Painted World of Ariamis", "strength": 23, "dexterity": 0, "intelligence": 0, "faith": 23},
    "Poison Gem": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 15, "intelligence": 0, "faith": 0},
    "Poison Gem": {"set": "Tomb of Giants", "strength": 0, "dexterity": 15, "intelligence": 0, "faith": 0},
    "Poison Mist": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 11, "intelligence": 16, "faith": 0},
    "Poison Mist": {"set": "Tomb of Giants", "strength": 0, "dexterity": 11, "intelligence": 16, "faith": 0},
    "Poison Throwing Knives": {"set": "Explorers", "strength": 0, "dexterity": 14, "intelligence": 14, "faith": 0},
    "Porcine Shield": {"set": "Iron Keep", "strength": 24, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Rapier": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 21, "intelligence": 21, "faith": 0},
    "Rapier": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 21, "intelligence": 21, "faith": 0},
    "Raw Gem": {"set": "Explorers", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Red and White Round Shield": {"set": "Tomb of Giants", "strength": 0, "dexterity": 0, "intelligence": 22, "faith": 10},
    "Red Tearstone Ring": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 20},
    "Reinforced Club": {"set": "Dark Souls The Board Game", "strength": 23, "dexterity": 0, "intelligence": 0, "faith": 16},
    "Reinforced Club": {"set": "Painted World of Ariamis", "strength": 23, "dexterity": 0, "intelligence": 0, "faith": 16},
    "Rotten Ghru Spear": {"set": "Darkroot", "strength": 0, "dexterity": 21, "intelligence": 12, "faith": 0},
    "Scimitar": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 20, "intelligence": 18, "faith": 0},
    "Scimitar": {"set": "Tomb of Giants", "strength": 0, "dexterity": 20, "intelligence": 18, "faith": 0},
    "Sharp Gem": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 25, "intelligence": 0, "faith": 0},
    "Sharp Gem": {"set": "Tomb of Giants", "strength": 0, "dexterity": 25, "intelligence": 0, "faith": 0},
    "Shortsword": {"set": "Dark Souls The Board Game", "strength": 15, "dexterity": 23, "intelligence": 0, "faith": 0},
    "Shortsword": {"set": "Painted World of Ariamis", "strength": 15, "dexterity": 23, "intelligence": 0, "faith": 0},
    "Silver Eagle Kite Shield": {"set": "Dark Souls The Board Game", "strength": 15, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Silver Eagle Kite Shield": {"set": "Painted World of Ariamis", "strength": 15, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Silver Knight Armour": {"set": "Explorers", "strength": 26, "dexterity": 26, "intelligence": 0, "faith": 0},
    "Silver Knight Spear": {"set": "Explorers", "strength": 0, "dexterity": 22, "intelligence": 0, "faith": 26},
    "Silver Knight Straight Sword": {"set": "Dark Souls The Board Game", "strength": 20, "dexterity": 20, "intelligence": 20, "faith": 20},
    "Silver Knight Straight Sword": {"set": "Painted World of Ariamis", "strength": 20, "dexterity": 20, "intelligence": 20, "faith": 20},
    "Simple Gem": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 15},
    "Simple Gem": {"set": "Tomb of Giants", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 15},
    "Skull Lantern": {"set": "Tomb of Giants", "strength": 0, "dexterity": 13, "intelligence": 14, "faith": 0},
    "Sorcerer's Staff": {"set": "Dark Souls The Board Game", "strength": 15, "dexterity": 0, "intelligence": 30, "faith": 0},
    "Sorcerer's Staff": {"set": "Painted World of Ariamis", "strength": 15, "dexterity": 0, "intelligence": 30, "faith": 0},
    "Soul Arrow": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 16, "faith": 0},
    "Soul Arrow": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 16, "faith": 0},
    "Soul Spear": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 25, "faith": 15},
    "Soulstream": {"set": "Dark Souls The Board Game", "strength": 0, "dexterity": 0, "intelligence": 22, "faith": 0},
    "Soulstream": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 22, "faith": 0},
    "Stone Greataxe": {"set": "Darkroot", "strength": 35, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Stone Greatshield": {"set": "Darkroot", "strength": 33, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Stone Greatsword": {"set": "Darkroot", "strength": 22, "dexterity": 0, "intelligence": 0, "faith": 22},
    "Stone Knight Armour": {"set": "Darkroot", "strength": 30, "dexterity": 0, "intelligence": 0, "faith": 0},
    "Sunless Armour": {"set": "Dark Souls The Board Game", "strength": 13, "dexterity": 0, "intelligence": 0, "faith": 13},
    "Sunless Armour": {"set": "Tomb of Giants", "strength": 13, "dexterity": 0, "intelligence": 0, "faith": 13},
    "Sunlight Shield": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 30},
    "Sunset Armour": {"set": "Dark Souls The Board Game", "strength": 20, "dexterity": 0, "intelligence": 0, "faith": 24},
    "Sunset Armour": {"set": "Tomb of Giants", "strength": 20, "dexterity": 0, "intelligence": 0, "faith": 24},
    "Thorolund Talisman": {"set": "Tomb of Giants", "strength": 0, "dexterity": 0, "intelligence": 0, "faith": 31},
    "Thrall Axe": {"set": "Dark Souls The Board Game", "strength": 16, "dexterity": 16, "intelligence": 0, "faith": 0},
    "Thrall Axe": {"set": "Tomb of Giants", "strength": 16, "dexterity": 16, "intelligence": 0, "faith": 0},
    "Throwing Knives": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 14, "intelligence": 12, "faith": 0},
    "Ughigatana": {"set": "Explorers", "strength": 0, "dexterity": 32, "intelligence": 0, "faith": 14},
    "Velka's Rapier": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 19, "intelligence": 27, "faith": 0},
    "Winged Spear": {"set": "Dark Souls The Board Game", "strength": 20, "dexterity": 0, "intelligence": 0, "faith": 22},
    "Winged Spear": {"set": "Tomb of Giants", "strength": 20, "dexterity": 0, "intelligence": 0, "faith": 22},
    "Witch's Lock": {"set": "Iron Keep", "strength": 0, "dexterity": 0, "intelligence": 31, "faith": 0},
    "Worker Armour": {"set": "Dark Souls The Board Game", "strength": 12, "dexterity": 12, "intelligence": 12, "faith": 12},
    "Worker Armour": {"set": "Painted World of Ariamis", "strength": 12, "dexterity": 12, "intelligence": 12, "faith": 12},
    "Xanthous Robes": {"set": "Painted World of Ariamis", "strength": 0, "dexterity": 0, "intelligence": 23, "faith": 20},
    "Zweihander": {"set": "Dark Souls The Board Game", "strength": 35, "dexterity": 25, "intelligence": 0, "faith": 0},
    "Zweihander": {"set": "Tomb of Giants", "strength": 35, "dexterity": 25, "intelligence": 0, "faith": 0}
}


def generate_treasure_soul_cost(setsAvailable):
    for treasure in treasures:
        treasures[treasure]["soulCost"] = mean_soul_cost(treasures[treasure], setsAvailable)


def pick_treasure(swapTreasure, setsAvailable):
    lower = treasures[swapTreasure]["soulCost"] - 1
    upper = treasures[swapTreasure]["soulCost"] + 1
    alts = [swapTreasure]
    alts += [t for t in treasures if lower <= treasures[t]["soulCost"] <= upper and treasures[t]["set"] in setsAvailable]
    alts = list(set(alts))
    return choice(alts)
